apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-script
  name: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-script
  template:
    metadata:
      labels:
        app: data-script
    spec:
      containers:
      - image: nursultanken/quotes-data-script:v2
        name: data-script
        env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: host
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: username
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: password
      initContainers:
       - name: init-datascript
         image: nursultanken/quotes-data-script:v2
         command: ['sh', '-c', "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo waiting for mydb; sleep 2; done"]
         env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: host
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: username
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: password
